'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Calculator,ArrowUpRight,Users,Info,Plus,Trash2,Check,ArrowRight,Undo2,CircleDollarSign,Wallet,TrendingUp} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Trend,Composition} from '@/components/pricing-charts';
import {calculate,demo,money,pct,validate,breakEven,unit,type Plan,type Cost} from '@/lib/pricing';
import {ProjectHistory} from '@/components/project-history';
import {PriceLibrary} from '@/components/price-library';
type Key='paying'|'free'|'price'|'tax'|'target'|'adultsPerFamily'|'childrenPerFamily'|'commission'|'reserve';
const modes=[{value:'fixed',label:'固定数量'},{value:'person',label:'按参与人数'},{value:'batch',label:'按容量分批'},{value:'adult',label:'按成人'},{value:'child',label:'按儿童'},{value:'family',label:'按家庭组数'}];
const safeValue=(n:number)=>Number.isFinite(n)?n:'';
const parse=(value:string)=>value===''?NaN:Number(value);
const quote=(n:number|null)=>n===null?null:Math.max(0,Math.ceil((n-1e-9)*100)/100);

export default function Home(){
const [plan,setPlan]=useState<Plan>(structuredClone(demo));
const adultGroup=['adult','senior','company'].includes(plan.groupType??'student');const family=plan.billing==='family';const billingUnit=unit(plan);
const [title,setTitle]=useState('');
const [edited,setEdited]=useState(false);
const [deleted,setDeleted]=useState<Cost|null>(null);
const ref=useRef(plan);ref.current=plan;
const errors=useMemo(()=>validate(plan),[plan]);
const result=useMemo(()=>errors.length?null:calculate(plan),[plan,errors]);
const first=useMemo(()=>errors.length?null:breakEven(plan),[plan,errors]);
function update(next:Plan){setPlan(next);setEdited(true)}
function setCost(id:string,patch:Partial<Cost>){update({...plan,costs:plan.costs.map(c=>c.id===id?{...c,...patch}:c)})}
useEffect(()=>{
type Context={registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>};
const context=(document as Document&{modelContext?:Context}).modelContext;
if(!context?.registerTool)return;
const lifecycle=new AbortController();
const register=(tool:object)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
register({name:'read_pricing',title:'读取研学定价测算',description:'读取当前页面参数、成本明细和计算结果。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>{const p=ref.current;const e=validate(p);return {plan:p,errors:e,result:e.length?null:calculate(p)}}});
register({name:'configure_pricing',title:'设置研学定价参数',description:'更新当前页面的售价、收费人数、免费随行人数、税费比例或目标毛利率，并重新计算。金额单位为元，比例用百分数。',inputSchema:{type:'object',properties:{paying:{type:'integer',minimum:0,maximum:10000},free:{type:'integer',minimum:0,maximum:10000},price:{type:'number',minimum:0,maximum:1000000},tax:{type:'number',minimum:0,maximum:100},target:{type:'number',minimum:0,maximum:100}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:(input:unknown)=>{
if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('参数须为对象');
const patch=input as Record<string,unknown>;
if(Object.keys(patch).some(k=>!['paying','free','price','tax','target'].includes(k)||typeof patch[k]!=='number'))throw new Error('参数字段或数值无效');
const next={...ref.current,...patch} as Plan;const e=validate(next);if(e.length)throw new Error(e.join('；'));
flushSync(()=>{setPlan(next);setEdited(true)});ref.current=next;return {result:calculate(next)};
}});
return()=>lifecycle.abort();
},[]);
function field(key:Key,label:string,unit:string){
return <label className="field"><span>{label}</span><div className="input-wrap"><Input type="number" min={0} max={['tax','target','commission','reserve'].includes(key)?100:['adultsPerFamily','childrenPerFamily'].includes(key)?10:key==='price'?1000000:10000} step={['paying','free','adultsPerFamily','childrenPerFamily'].includes(key)?1:'any'} value={safeValue(plan[key]??(['adultsPerFamily','childrenPerFamily'].includes(key)?1:0))} onChange={e=>update({...plan,[key]:parse(e.target.value)})}/><em>{unit}</em></div></label>;
}
const verdict=!result?'请补全有效数据':plan.paying===0?'还没有收费学员':result.base===0?'请先核实成本是否完整':result.revenue===0?'当前收入为零':result.profit<0?'当前定价无法覆盖成本':result.margin!==null&&result.margin+1e-9>=plan.target/100?'成本可覆盖，达到目标毛利率':'成本可覆盖，尚未达到目标';
const healthy=!!result&&result.base>0&&result.revenue>0&&result.margin!==null&&result.margin+1e-9>=plan.target/100;
return <><header className="topbar"><div className="brand"><span className="brand-icon"><Calculator size={23}/></span>研学定价台<span className="brand-caption">PRICING LAB</span></div><nav className="main-nav" aria-label="页面导航"><a href="#project-library-title">项目档案</a><a href="#price-library-heading">价格数据库</a><a href="#cost-heading">成本明细</a><a href="#method">计算口径 <ArrowUpRight size={15}/></a></nav></header><main className="workspace">
<div className="page-title"><div><p className="eyebrow">项目测算 / {edited?'当前方案':'演示方案 · 请替换为实际成本'}</p><h1>研学项目成本测算</h1></div><span className="live"><i/>实时测算</span></div>
<ProjectHistory plan={plan} title={title} onTitle={setTitle} valid={errors.length===0} onLoad={(p,t)=>{update(p);setTitle(t);setDeleted(null);}}/>
<div className="workspace-grid"><aside className="panel parameters"><div className="section-title"><h2>项目参数</h2><Users size={20}/></div><p className="muted">先填人数和售价，再完善下方成本。</p><label className="field"><span>收费模式</span><Select items={[{value:'person',label:'按人收费'},{value:'family',label:'按家庭组收费'}]} value={plan.billing??'person'} onValueChange={value=>{if(value)update({...plan,billing:value as Plan['billing'],groupType:value==='family'?'family':plan.groupType==='family'?'student':plan.groupType})}}><SelectTrigger aria-label="收费模式"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="person">按人收费</SelectItem><SelectItem value="family">按家庭组收费</SelectItem></SelectContent></Select></label>{family&&<><div className="two-fields">{field('adultsPerFamily','每组成人','人')}{field('childrenPerFamily','每组儿童','人')}</div><p className="field-note">一组是一户家庭，默认 1 大 1 小。切换模式保留原数值，请核对组数和整组售价。</p></>}{field('price',family?'每组售价':'对外售价','元 / '+billingUnit)}<div className="two-fields">{field('paying',family?'收费组数':adultGroup?'收费成人':'收费学生/儿童',billingUnit)}{field('free','免费随行成人','人')}</div><div className="attendees">实际参与人数 <strong>{result?.attendees??'—'} 人</strong></div><p className="field-note">成人 {result?.adults??'—'} 人 · 儿童 {result?.children??'—'} 人。免费随行按成人计，其他特殊人数可用固定数量录入成本。</p><div className="separator"/>{field('target','目标毛利率','%')}{field('tax','按收入计提的税费','%')}{field('commission','渠道佣金（按收入）','%')}{field('reserve','成本预备金（按明细）','%')}<p className="field-note">税费比例由你确定；设为 0 表示不计提。</p><div className="local-note"><Info size={17}/><span>计算无需登录。填写项目主题后，可登录保存到云端并随时查询。</span></div></aside>
<section className="results"><div className={'verdict '+(!healthy?'caution':'')} aria-live="polite"><span className="eyebrow">定价判断 · 实际成本口径</span><h2>{verdict}</h2><p>{result&&result.targetPrice!==null&&result.base>0&&result.revenue>0?healthy?'当前售价高于目标定价 ¥'+money(Math.max(0,plan.price-result.targetPrice))+' / '+billingUnit+'。':'达到目标，售价需调整至至少 ¥'+money(quote(result.targetPrice))+' / '+billingUnit+'。':'补全所有成本后，再判断定价是否满足项目目标。'}</p>{healthy&&<Check className="verdict-icon" size={28}/>}</div>
{errors.length>0?<div role="alert" className="error-box">{errors.join('；')}</div>:result&&<><div className="metrics"><article><span><CircleDollarSign size={17}/>预计收入</span><strong>¥{money(result.revenue)}</strong><small>{plan.paying} {billingUnit}付费 × ¥{money(plan.price)}</small></article><article><span><Wallet size={17}/>实际总成本</span><strong>¥{money(result.actual)}</strong><small>含税费、渠道佣金与成本预备金</small></article><article className={'profit '+(result.profit<0?'negative':'')}><span><TrendingUp size={17}/>预计实际毛利</span><strong>¥{money(result.profit)}</strong><small>实际毛利率 {pct(result.margin)}</small></article></div>
<div className="panel quick-result"><div><span className="eyebrow">达到 {plan.target}% 毛利率的售价</span><h2>¥{money(quote(result.targetPrice))}<small> / {billingUnit}</small></h2><p>{result.targetPrice===null?plan.paying===0?'请先设置收费人数。':'税费、佣金与目标毛利率之和须小于 100%。':'按当前人数与成本计算，向上取整到分。'}</p>{result.targetPrice!==null&&result.targetPrice<=1000000&&<Button className="use-price" variant="outline" onClick={()=>update({...plan,price:quote(result.targetPrice)!})}>采用此售价 <ArrowRight size={15}/></Button>}</div><div><span>保本价格</span><strong>¥{money(quote(result.breakPrice))} / {billingUnit}</strong><p>{result.breakPrice===null?'当前人数或税费设置下无法计算。':'按当前规模，恰好覆盖实际总成本。'}</p></div></div></>}
</section></div>
{result&&<div className="charts-grid"><Trend plan={plan} first={first}/><Composition plan={plan}/></div>}
<PriceLibrary plan={plan} onPlan={update}/>
<section className="panel cost-editor" aria-labelledby="cost-heading"><div className="editor-heading"><div><div className="section-title"><h2 id="cost-heading">成本明细</h2><span className="tag">{plan.costs.length} 个项目</span></div><p className="muted">成人和儿童可分别录入不同票价；按容量分批用于车辆等资源，数量向上取整。按家庭组数仅用于亲子团。</p></div><Button className="add-cost" disabled={plan.costs.length>=100} onClick={()=>update({...plan,costs:[...plan.costs,{id:crypto.randomUUID(),name:'新增成本',mode:'fixed',amount:0,quantity:1,capacity:1,actualOnly:false}]})}><Plus size={17}/>添加成本</Button></div>
<Table className="cost-table"><TableHeader><TableRow><TableHead>成本项目</TableHead><TableHead>计费方式</TableHead><TableHead>单价 / 元</TableHead><TableHead>数量 / 批次容量</TableHead><TableHead>仅计入实际成本 <a href="#method" aria-label="了解实际成本口径">ⓘ</a></TableHead><TableHead className="amount-cell">合计 / 元</TableHead><TableHead><span className="sr-only">操作</span></TableHead></TableRow></TableHeader><TableBody>{plan.costs.map(c=><TableRow key={c.id}><TableCell><Input className="cost-name" aria-label={c.name+' 项目名称'} maxLength={60} value={c.name} onChange={e=>setCost(c.id,{name:e.target.value})}/>{c.priceOrigin&&<small className="price-origin">{c.priceOrigin.catalogName} · v{c.priceOrigin.version} · 原单价 ¥{money(c.priceOrigin.unitPrice)}{c.amount!==c.priceOrigin.unitPrice?' · 已手动调整':''}</small>}</TableCell><TableCell><Select items={modes} value={c.mode} onValueChange={value=>{if(value)setCost(c.id,{mode:value as Cost['mode']})}}><SelectTrigger aria-label={c.name+' 计费方式'} className="mode-select"><SelectValue/></SelectTrigger><SelectContent>{modes.map(m=><SelectItem key={m.value} value={m.value}>{m.label}</SelectItem>)}</SelectContent></Select></TableCell><TableCell><Input className="cost-number" aria-label={c.name+' 单价'} type="number" min={0} max={10000000} step="any" value={safeValue(c.amount)} onChange={e=>setCost(c.id,{amount:parse(e.target.value)})}/></TableCell><TableCell>{['person','adult','child','family'].includes(c.mode)?<span className="auto-quantity">{result?(c.mode==='adult'?result.adults:c.mode==='child'?result.children:c.mode==='family'?result.families:result.attendees):'—'} {c.mode==='family'?'组':'人'} · 自动</span>:<div className="quantity-input"><Input aria-label={c.name+(c.mode==='batch'?' 批次容量':' 数量')} type="number" min={c.mode==='batch'?1:0} max={c.mode==='batch'?20000:10000} step={c.mode==='batch'?1:'any'} value={safeValue(c.mode==='batch'?c.capacity:c.quantity)} onChange={e=>setCost(c.id,{[c.mode==='batch'?'capacity':'quantity']:parse(e.target.value)})}/><span>{c.mode==='batch'?'人 / 批':'份'}</span></div>}</TableCell><TableCell className="check-cell"><Checkbox checked={c.actualOnly} onCheckedChange={checked=>setCost(c.id,{actualOnly:checked===true})} aria-label={c.name+' 仅计入实际成本'}/></TableCell><TableCell className="amount-cell">{result?money(result.items.find(x=>x.id===c.id)?.total??0):'—'}</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={'删除 '+c.name} onClick={()=>{setDeleted(c);update({...plan,costs:plan.costs.filter(x=>x.id!==c.id)})}}><Trash2 size={16}/></Button></TableCell></TableRow>)}{plan.costs.length===0&&<TableRow><TableCell colSpan={7} className="empty-cost">尚无成本项目。点击“添加成本”开始填写。</TableCell></TableRow>}</TableBody></Table>
{deleted&&<div className="undo-row"><span>已删除“{deleted.name}”</span><Button variant="ghost" size="sm" disabled={plan.costs.length>=100} onClick={()=>{update({...plan,costs:[...plan.costs,deleted]});setDeleted(null)}}><Undo2 size={14}/>撤销</Button></div>}
<div className="cost-summary"><span>成本项目合计 <strong>¥{money(result?.subtotal??null)}</strong></span><span>成本预备金 <strong>¥{money(result?.reserveCost??null)}</strong></span><span>渠道佣金 <strong>¥{money(result?.commissionCost??null)}</strong></span><span>收入计提税费 <strong>¥{money(result?.taxCost??null)}</strong></span><span>实际总成本 <strong>¥{money(result?.actual??null)}</strong></span></div></section>
{result&&<div className="analysis-grid"><section className="panel comparison"><div className="section-title"><h2>换个售价，会怎样？</h2><span className="tag">当前人数不变</span></div><Table><TableHeader><TableRow><TableHead>售价方案</TableHead><TableHead className="amount-cell">{family?'每组售价':'人均售价'}</TableHead><TableHead className="amount-cell">实际毛利</TableHead><TableHead className="amount-cell">毛利率</TableHead></TableRow></TableHeader><TableBody>{[.9,1,1.1].map((scale,i)=>{const price=Math.round(plan.price*scale*100)/100;const r=calculate(plan,plan.paying,price);return <TableRow className={scale===1?'current-scenario':''} key={scale}><TableCell>{['降价 10%','当前售价','提价 10%'][i]}</TableCell><TableCell className="amount-cell">¥{money(price)}</TableCell><TableCell className={'amount-cell '+(r.profit<0?'loss':'')}>¥{money(r.profit)}</TableCell><TableCell className="amount-cell">{pct(r.margin)}</TableCell></TableRow>})}</TableBody></Table><p className="chart-note">各方案同步重算税费和渠道佣金。成本预备金按成本明细合计计提。</p></section><section className="panel reconciliation"><h2>两种成本口径，对照看</h2><p className="muted">“财务”沿用原表定义，定价判断统一使用实际口径。</p><div className="reconcile-head"><span/><span>财务口径</span><span>实际口径</span></div>{[['总成本',money(result.financial),money(result.actual)],['毛利',money(result.financialProfit),money(result.profit)],['毛利率',pct(result.financialMargin),pct(result.margin)]].map(row=><div className="reconcile-row" key={row[0]}>{row.map((cell,i)=>i===0?<span key={i}>{cell}</span>:<strong key={i}>{cell}</strong>)}</div>)}<p className="chart-note">两者相差 ¥{money(result.extra)}，来自勾选“仅计入实际成本”的费用，通常为带班费、操作费。</p></section></div>}
<section id="method" className="panel method"><h2>怎么算，也说清楚</h2><div className="method-grid"><div><h3>沿用原表的关系</h3><p>收入 = 收费人数（或家庭组数）× 对应售价。亲子团成人数 = 组数 × 每组成人 + 免费随行，儿童数 = 组数 × 每组儿童。成本预备金 = 明细合计 × 预备金比例；实际成本 = 明细合计 + 预备金 + 收入 ×（税费 + 佣金）比例。财务口径扣除勾选的仅计入实际费用，预备金保留在两种口径。</p><p>毛利 = 收入 − 对应口径成本。毛利率 = 毛利 ÷ 收入；收入为 0 时毛利率不显示。这里的毛利不等于扣除全部经营费用后的净利润。</p></div><div><h3>为定价增加的测算</h3><p>保本价 =（明细合计 + 预备金）÷ 收费人数或组数 ÷ (1 − 税费比例 − 佣金比例)。目标价再从分母扣除目标毛利率。亲子团的价格、分摊成本和招生曲线均以组为单位。</p><p>按容量分批数量 = 向上取整(实际参与人数 ÷ 批次容量)。首次保本在 1–10,000 个收费单位内逐一测算；免费随行人数固定，加车后可能再次亏损。</p></div></div><details><summary>原表对应关系与使用说明</summary><p>参考《收入成本表(计算表).xls》“收入成本表”：F32 汇总财务成本，I32 汇总实际成本，F33/I33 计算两种毛利，F34/I34 计算两种毛利率。原表的备用金、公对公、员工垫付、后结是支付渠道；本页按成本项目合计，同一费用请只录入一次。</p><p>原表收入公式使用的收费人数与表头人数不同，因此本页将收费人数与免费随行分开。固定采购数量可独立填写，按人数计费则默认覆盖所有参与者；如果只有部分人使用某项服务，请选择“固定数量”并填写实际数量。</p><p>原表税点单元格未自动计入金额，本页新增“收入 × 自填税费比例”的预算估算。它不是税务申报算法。所有单价按整次活动填写；多天餐饮、住宿可先合并为整次人均成本，或拆成多个项目。</p><p>示例费用仅供演示，请补全交通、材料、餐饮、保险、师资、场地等实际费用。达到目标毛利率只说明成本与利润目标匹配，不能单独判断市场接受度。点击“保存本次估算”后，项目主题及成本参数会存入当前账号的云端记录，仅该账号可查询。未保存的修改在刷新后会丢失。</p></details></section><footer>研学定价台 <span>每一个定价，都能追溯到成本。</span></footer></main></>;
}