'use client';
import {useEffect,useMemo,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Database,Upload,Check} from 'lucide-react';
import type {Cost,GroupType,Plan} from '@/lib/pricing';

type PriceItem={id:string;catalogId:string;groupType:GroupType;category:string;name:string;mode:Cost['mode'];amount:number;quantity:number;capacity:number;minPeople:number;maxPeople:number;actualOnly:boolean;note:string;sortOrder:number};
type Catalog={id:string;name:string;source:'system'|'user';updatedAt:string;items:PriceItem[]};
type Api={catalogs:Catalog[];needsLogin?:boolean;error?:string};
const groupOptions=[['student','学生团'],['family','亲子团'],['senior','老年团'],['adult','成人团'],['company','企业团'],['custom','自定义']] as const;
const modeMap:Record<string,Cost['mode']>={'固定数量':'fixed','fixed':'fixed','按参与人数':'person','按人数':'person','person':'person','按容量分批':'batch','batch':'batch','按成人':'adult','adult':'adult','按儿童':'child','child':'child','按家庭组数':'family','按家庭':'family','family':'family'};
const groupMap:Record<string,GroupType>={'学生团':'student','student':'student','亲子团':'family','family':'family','老年团':'senior','senior':'senior','成人团':'adult','adult':'adult','企业团':'company','company':'company','自定义':'custom','custom':'custom'};
function splitLine(line:string,sep:string){return line.split(sep).map(v=>v.trim().replace(/^"|"$/g,''));}
function parseRows(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('至少需要表头和 1 行价格数据');const sep=lines[0].includes('\t')?'\t':',';const headers=splitLine(lines[0],sep);const index=(...names:string[])=>headers.findIndex(h=>names.includes(h));const at=(cells:string[],...names:string[])=>{const i=index(...names);return i>=0?cells[i]:'';};return lines.slice(1).map((line,i)=>{const c=splitLine(line,sep),name=at(c,'项目名称','name'),amount=Number(at(c,'单价','amount')),group=groupMap[at(c,'团体类型','groupType')]||'student',mode=modeMap[at(c,'计费方式','mode')]||'person';if(!name||!Number.isFinite(amount))throw new Error(`第 ${i+2} 行缺少项目名称或有效单价`);return {groupType:group,category:at(c,'分类','category')||'其他',name,mode,amount,quantity:Number(at(c,'数量','quantity')||1),capacity:Number(at(c,'批次容量','capacity')||1),minPeople:Number(at(c,'最低人数','minPeople')||0),maxPeople:Number(at(c,'最高人数','maxPeople')||10000),note:at(c,'备注','note')};});}
export function PriceLibrary({plan,onPlan}:{plan:Plan;onPlan:(p:Plan)=>void}){
 const [source,setSource]=useState<'system'|'user'>('system'),[catalogs,setCatalogs]=useState<Catalog[]>([]),[catalogId,setCatalogId]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[showImport,setShowImport]=useState(false),[importName,setImportName]=useState('我的价格库'),[paste,setPaste]=useState(''),[preview,setPreview]=useState<Record<string,unknown>[]>([]);
 const groupType=plan.groupType??(plan.billing==='family'?'family':'student');
 useEffect(()=>{const controller=new AbortController();setLoading(true);setMessage('');fetch(`/api/price-library?source=${source}&group=${groupType}`,{cache:'no-store',signal:controller.signal}).then(r=>r.json()).then((data:Api)=>{if(data.error)throw new Error(data.error);setCatalogs(data.catalogs);setCatalogId(v=>data.catalogs.some(c=>c.id===v)?v:(data.catalogs[0]?.id??''));if(source==='user'&&data.needsLogin)setMessage('登录后可以导入和使用自己的价格库。');}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message||'价格库读取失败');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[source,groupType]);
 const catalog=useMemo(()=>catalogs.find(c=>c.id===catalogId)??catalogs[0],[catalogs,catalogId]);const eligible=(catalog?.items??[]).filter(x=>{const n=plan.billing==='family'?plan.paying:plan.paying+plan.free;return n>=x.minPeople&&n<=x.maxPeople;});
 function useItem(item:PriceItem){const next:Cost={id:crypto.randomUUID(),name:item.name,mode:item.mode,amount:item.amount,quantity:item.quantity||1,capacity:item.capacity||1,actualOnly:item.actualOnly};onPlan({...plan,costs:[...plan.costs,next]});setMessage(`已添加“${item.name}” ¥${item.amount}`);}
 function useAll(){const names=new Set(plan.costs.map(c=>c.name));const additions=eligible.filter(i=>!names.has(i.name)).map(i=>({id:crypto.randomUUID(),name:i.name,mode:i.mode,amount:i.amount,quantity:i.quantity||1,capacity:i.capacity||1,actualOnly:i.actualOnly}));onPlan({...plan,costs:[...plan.costs,...additions]});setMessage(additions.length?`已添加 ${additions.length} 条价格到成本明细。`:'这些项目已在成本明细中。');}
 async function importRows(){if(!preview.length)return;setLoading(true);setMessage('');try{const res=await fetch('/api/price-library',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:importName,rows:preview})});const data=await res.json();if(!res.ok)throw new Error(data.error||'导入失败');setMessage(`已导入 ${data.count} 条价格。`);setShowImport(false);setPreview([]);setPaste('');setSource('user');}catch(e){setMessage(e instanceof Error?e.message:'导入失败');}finally{setLoading(false);}}
 function previewText(text:string){setPaste(text);try{setPreview(parseRows(text));setMessage('');}catch(e){setPreview([]);if(text.trim())setMessage(e instanceof Error?e.message:'数据格式无效');}}
 return <section className="panel cost-editor" aria-labelledby="price-library-heading"><div className="editor-heading"><div><div className="section-title"><Database size={20}/><h2 id="price-library-heading">价格数据库</h2><span className="tag">{source==='system'?'平台标准':'我的价格库'}</span></div><p className="muted">按团体类型匹配固定价格，可单项采用或一键加入成本明细。</p></div><Button variant="outline" onClick={()=>setShowImport(v=>!v)}><Upload size={16}/>导入我的价格</Button></div>
 <div className="two-fields"><label className="field"><span>团体类型</span><Select value={groupType} onValueChange={v=>{if(!v)return;const g=v as GroupType;onPlan({...plan,groupType:g,billing:g==='family'?'family':plan.billing==='family'?'person':plan.billing});}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{groupOptions.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label><label className="field"><span>价格来源</span><Select value={source} onValueChange={v=>v&&setSource(v as 'system'|'user')}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="system">平台标准价格库</SelectItem><SelectItem value="user">我的价格库</SelectItem></SelectContent></Select></label></div>
 {catalogs.length>1&&<label className="field"><span>价格表</span><Select value={catalogId} onValueChange={v=>v&&setCatalogId(v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{catalogs.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></label>}
 {showImport&&<div className="restore-prompt"><div style={{width:'100%'}}><strong>导入个人价格库</strong><p className="field-note">支持 CSV 文件内容，或直接从 Excel 复制表格后粘贴。表头建议：团体类型、分类、项目名称、计费方式、单价、数量、批次容量、最低人数、最高人数、备注。</p><Input value={importName} maxLength={80} onChange={e=>setImportName(e.target.value)} placeholder="例如：2026秋季学校团队价格表"/><textarea value={paste} onChange={e=>previewText(e.target.value)} rows={7} style={{width:'100%',marginTop:12,padding:12,border:'1px solid var(--border)',borderRadius:8}} placeholder={'团体类型\t分类\t项目名称\t计费方式\t单价\n学生团\t门票\t学生票\t按儿童\t30\n学生团\t保险\t活动保险\t按人数\t5'}/><div style={{display:'flex',gap:8,marginTop:10,alignItems:'center'}}><Button disabled={!preview.length||loading||!importName.trim()} onClick={importRows}><Check size={16}/>确认导入 {preview.length||''}</Button><Button variant="outline" onClick={()=>{setShowImport(false);setPreview([]);setPaste('')}}>取消</Button></div></div></div>}
 {message&&<p role="status" className="history-message">{message}</p>}
 {loading?<p className="muted">正在读取价格库…</p>:eligible.length?<><div className="editor-heading"><div><strong>{catalog?.name}</strong><p className="field-note">已匹配 {eligible.length} 条当前团型价格。平台初始数据为示例价，请按实际政策维护。</p></div><Button onClick={useAll}>全部添加到成本明细</Button></div><Table><TableHeader><TableRow><TableHead>分类</TableHead><TableHead>项目</TableHead><TableHead>计费方式</TableHead><TableHead>参考价</TableHead><TableHead>备注</TableHead><TableHead/></TableRow></TableHeader><TableBody>{eligible.map(item=><TableRow key={item.id}><TableCell>{item.category}</TableCell><TableCell><strong>{item.name}</strong></TableCell><TableCell>{item.mode}</TableCell><TableCell>¥{item.amount}</TableCell><TableCell>{item.note||'—'}</TableCell><TableCell><Button variant="outline" size="sm" onClick={()=>useItem(item)}>采用</Button></TableCell></TableRow>)}</TableBody></Table></>:<p className="history-empty">当前团体类型还没有可用价格。可以切换价格来源，或导入自己的价格表。</p>}
 </section>;
}
