'use client';
import {calculate,money,pct,unit,type Plan} from '@/lib/pricing';
const colors=['#2457e6','#5d87f5','#f3a34c','#23a79e','#9469d6','#a9b9d6','#df677b'];
export function Trend({plan,first}:{plan:Plan;first:number|null}){
const u=unit(plan);
const maxN=Math.min(10000,Math.max(20,Math.ceil(plan.paying*1.7),first!==null?Math.ceil(first*1.25):0));
const count=Math.min(maxN,80);
const points=Array.from(new Set([0,plan.paying,...Array.from({length:count+1},(_,i)=>Math.round(i*maxN/count))])).sort((a,b)=>a-b).map(n=>({n,...calculate(plan,n)}));
const maxY=Math.max(1,...points.map(p=>Math.max(p.revenue,p.actual)))*1.12;
const x=(n:number)=>64+n/maxN*616,y=(v:number)=>232-v/maxY*190;
const compact=(v:number)=>new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(v);
return <section className="panel chart-panel"><div className="section-title"><h2>多少{u}成团，才不亏？</h2><span className="tag">招生敏感性</span></div><div className="chart-sub"><span>首次保本 <strong>{first??('10,000 '+u+'内未找到')}{first?' '+u:''}</strong></span><div className="legend"><span><i style={{background:colors[0]}}/>收入</span><span><i style={{background:colors[2]}}/>实际成本</span></div></div><div className="trend-scroll"><svg className="trend" viewBox="0 0 720 280" role="img" aria-label={'收入和实际成本随收费'+u+'数变化，首次保本为'+(first===null?'一万个收费单位内未找到':first+u)}><title>招生数量与收入、实际成本</title><desc>免费随行人数保持不变，按人数和按组成本随收费人数联动。蓝线为收入，橙线为实际成本。</desc>{[0,1,2,3,4].map(i=><g key={i}><line x1="64" x2="680" y1={y(maxY*i/4)} y2={y(maxY*i/4)} stroke="#e7ecf4" strokeDasharray="4 5"/><text x="54" y={y(maxY*i/4)+4} textAnchor="end">{compact(maxY*i/4)}</text></g>)}<text x="18" y="21">金额 / 元</text>{[0,.25,.5,.75,1].map(v=><text key={v} x={x(maxN*v)} y="254" textAnchor="middle">{Math.round(maxN*v)}</text>)}<text x="680" y="277" textAnchor="end">收费数量 / {u}</text><polyline fill="none" stroke={colors[2]} strokeWidth="3" points={points.map(p=>x(p.n)+','+y(p.actual)).join(' ')}/><polyline fill="none" stroke={colors[0]} strokeWidth="3" points={points.map(p=>x(p.n)+','+y(p.revenue)).join(' ')}/><line x1={x(plan.paying)} x2={x(plan.paying)} y1="28" y2="233" stroke="#7f97c9" strokeDasharray="5 4"/><text x={Math.min(650,Math.max(94,x(plan.paying)))} y="18" textAnchor="middle" fill="#2457e6">当前 {plan.paying} {u}</text><circle cx={x(plan.paying)} cy={y(calculate(plan).revenue)} r="5" fill={colors[0]} stroke="white" strokeWidth="2"/></svg></div><p className="chart-note">免费随行人数固定。按组费用会随人数跳增；首次保本后仍可能再次亏损。曲线按整数收费单位抽样。</p></section>;
}
export function Composition({plan}:{plan:Plan}){
const r=calculate(plan);
const all=[...r.items.filter(c=>c.total>0).map(c=>({name:c.name||'未命名成本',total:c.total})),...(r.reserveCost>0?[{name:'成本预备金',total:r.reserveCost}]:[]),...(r.commissionCost>0?[{name:'渠道佣金',total:r.commissionCost}]:[]),...(r.taxCost>0?[{name:'收入计提税费',total:r.taxCost}]:[])].sort((a,b)=>b.total-a.total);
const parts=all.length>6?[...all.slice(0,5),{name:'其他成本（'+(all.length-5)+' 项）',total:all.slice(5).reduce((s,c)=>s+c.total,0)}]:all;
let start=0;const arcs=parts.map((p,i)=>{const f=r.actual>0?p.total/r.actual:0;const offset=start;start+=f;return {...p,f,offset,color:colors[i%colors.length]}});
return <section className="panel chart-panel composition"><div className="section-title"><h2>成本花在哪里？</h2><span className="tag">实际口径</span></div><div className="donut-wrap"><svg viewBox="0 0 220 220" role="img" aria-label="各成本项目占实际总成本的比例"><circle cx="110" cy="110" r="82" fill="none" stroke="#edf1f8" strokeWidth="23"/>{arcs.map((a,i)=><circle key={i} cx="110" cy="110" r="82" fill="none" stroke={a.color} strokeWidth="23" pathLength="100" strokeDasharray={a.f*100+' '+(100-a.f*100)} strokeDashoffset={-a.offset*100} transform="rotate(-90 110 110)"><title>{a.name+'：¥'+money(a.total)+'，'+pct(a.f)}</title></circle>)}<text x="110" y="103" textAnchor="middle" className="donut-caption">每{unit(plan)}分摊</text><text x="110" y="132" textAnchor="middle" className="donut-value">¥{money(r.perPerson)}</text></svg></div><div className="cost-legend">{arcs.map((a,i)=><div key={i}><i style={{background:a.color}}/><span>{a.name}</span><strong>¥{money(a.total)}</strong><small>{pct(a.f)}</small></div>)}{!arcs.length&&<p className="chart-note">添加成本后显示占比。</p>}</div></section>;
}