'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Save,Search,Cloud,FolderOpen,Trash2,Pencil,Download} from 'lucide-react';
import {money,type Plan} from '@/lib/pricing';
import {GoogleSignIn} from '@/components/google-sign-in';
import {exportEstimate} from '@/lib/estimate-export';
import {parseEstimate} from '@/lib/estimate-input';
type RecordItem={billing?:'person'|'family';id:string;title:string;createdAt:string;paying:number;price:number;actual:number;profit:number};
type Saved={id:string;title:string;createdAt:string;plan:Plan};
type Account={user:{displayName:string;email:string}|null;clientId:string|null};
const date=(value:string)=>new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
async function request<T=unknown>(url:string,init?:RequestInit){const res=await fetch(url,{...init,cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error((data as {error?:string}).error||'操作失败，请重试');return data as T;}
export function ProjectHistory({plan,title,onTitle,onLoad,valid}:{plan:Plan;title:string;onTitle:(v:string)=>void;onLoad:(p:Plan,t:string)=>void;valid:boolean}){
 const [account,setAccount]=useState<Account|null>(null),[accountError,setAccountError]=useState('');
 const [items,setItems]=useState<RecordItem[]>([]),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(false),[historyError,setHistoryError]=useState(''),[revision,setRevision]=useState(0);
 const [saving,setSaving]=useState(false),[message,setMessage]=useState(''),[opening,setOpening]=useState<string|null>(null),[pending,setPending]=useState<Saved|null>(null);
 const [editing,setEditing]=useState<Saved|null>(null),[pendingEdit,setPendingEdit]=useState(false),[deleting,setDeleting]=useState<RecordItem|null>(null);
 const submission=useRef<{body:string;id:string}|null>(null);const loadRef=useRef(onLoad);useEffect(()=>{loadRef.current=onLoad;},[onLoad]);
 async function loadAccount(){setAccountError('');try{setAccount(await request<Account>('/api/account'));window.dispatchEvent(new Event('pricing-account-changed'));}catch{setAccountError('暂时无法连接账号服务');}}
 useEffect(()=>{void Promise.resolve().then(loadAccount);try{const raw=sessionStorage.getItem('pricing-login-draft');if(raw){const value=parseEstimate(JSON.parse(raw));loadRef.current(value.plan,value.title);sessionStorage.removeItem('pricing-login-draft');}}catch{}},[]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{if(!account?.user){setItems([]);setPending(null);return;}setLoading(true);setHistoryError('');request<{items:RecordItem[];hasMore:boolean}>('/api/estimates?q='+encodeURIComponent(query)+'&offset='+offset,{signal:controller.signal}).then(data=>{if(!controller.signal.aborted){setItems(data.items);setHasMore(data.hasMore);}}).catch(e=>{if(!controller.signal.aborted)setHistoryError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);controller.abort();};},[account,query,offset,revision]);
 async function save(){if(saving||opening)return;setMessage('');let value;try{const body=JSON.stringify({title,plan});if(submission.current?.body!==body)submission.current={body,id:crypto.randomUUID()};value=parseEstimate({id:editing?.id??submission.current.id,title,plan});}catch(e){setMessage(e instanceof Error?e.message:'请完善项目参数');return;}setSaving(true);try{await request('/api/estimates',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});setMessage((editing?'已更新':'已保存')+'“'+value.title+'”。可在下方历史记录中查询。');if(editing)setEditing({...editing,title:value.title,plan:value.plan});setQuery('');setOffset(0);setRevision(v=>v+1);}catch(e){setMessage(e instanceof Error?e.message:'保存失败，请重试');}finally{setSaving(false);}}
 async function open(id:string,edit=false){setOpening(id);setMessage('');setPending(null);setPendingEdit(edit);setDeleting(null);try{setPending(await request<Saved>('/api/estimates?id='+encodeURIComponent(id)));}catch(e){setMessage(e instanceof Error?e.message:'读取失败，请重试');}finally{setOpening(null);}}
 async function remove(){if(!deleting||opening)return;setOpening(deleting.id);setMessage('');try{await request('/api/estimates?id='+encodeURIComponent(deleting.id),{method:'DELETE'});if(editing?.id===deleting.id){setEditing(null);submission.current=null;}if(pending?.id===deleting.id)setPending(null);setDeleting(null);if(items.length===1&&offset>0)setOffset(v=>Math.max(0,v-20));setRevision(v=>v+1);setMessage('已删除历史估算。');}catch(e){setMessage(e instanceof Error?e.message:'删除失败，请重试');}finally{setOpening(null);}}
 async function download(id:string){setOpening(id);setMessage('');try{const saved=await request<Saved>('/api/estimates?id='+encodeURIComponent(id));const file=await exportEstimate(saved);const url=URL.createObjectURL(file.content);const link=document.createElement('a');link.href=url;link.download=file.filename;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('已导出“'+saved.title+'”的云端记录（Excel，含项目参数、成本明细和测算结果）。');}catch(e){setMessage(e instanceof Error?e.message:'导出失败，请重试');}finally{setOpening(null);}}
 async function logout(){try{await request('/api/auth/logout',{method:'POST'});window.location.reload();}catch(e){setMessage(e instanceof Error?e.message:'退出失败，请重试');}}
 function keepDraft(){try{if(valid)sessionStorage.setItem('pricing-login-draft',JSON.stringify({id:crypto.randomUUID(),title:title.trim()||'未命名项目',plan}));}catch{}}
 return <section className="panel project-library" aria-labelledby="project-library-title"><div className="editor-heading"><div><div className="section-title"><span className="project-folder"><FolderOpen size={21}/></span><h2 id="project-library-title">项目档案</h2><span className="cloud-label"><Cloud size={14}/>云端保存</span></div><p className="muted">为每次估算命名，让历史成本有据可查。</p></div><div className="account-area">{account?.user?<><span>{account.user.displayName}</span><Button variant="ghost" size="sm" onClick={logout}>退出登录</Button></>:account?account.clientId?<GoogleSignIn clientId={account.clientId} onSuccess={()=>{setMessage('Google 登录成功，现在可以保存和查询项目。');void loadAccount();}}/>:<span role="alert">Google 登录暂不可用，请稍后重试。</span>:accountError?<><span role="alert">{accountError}</span><Button variant="outline" onClick={loadAccount}>重试</Button></>:<span>正在连接账号…</span>}</div></div>
 <div className="project-save"><label className="field" htmlFor="estimate-title"><span>项目主题名称</span><Input id="estimate-title" maxLength={80} placeholder="例如：秋季自然探索 · 杭州一日研学" value={title} onChange={e=>onTitle(e.target.value)}/></label><Button disabled={!account?.user||saving||opening!==null||!valid||!title.trim()} onClick={save}><Save size={17}/>{saving?'正在保存…':editing?'保存修改':'保存本次估算'}</Button></div>
 <p className="field-note">{editing?'正在修改“'+editing.title+'”，保存修改将更新这条历史记录。':'保存完整参数和成本明细；载入后保存会新增记录。'}未点击保存的修改不会自动同步。{!account?.user&&'计算无需登录，云端保存与查询需要登录。'}</p>
 {editing&&<div className="restore-prompt"><span>编辑模式：可修改上方名称及下方项目参数、成本明细。</span><Button variant="outline" disabled={saving} onClick={()=>{onLoad(structuredClone(editing.plan),editing.title);setEditing(null);submission.current=null;setMessage('已退出修改，恢复为最近保存的内容。');}}>取消修改</Button></div>}
 {deleting&&<div className="restore-prompt" role="alert"><span>确定删除“{deleting.title}”？删除后无法恢复。</span><Button variant="destructive" disabled={opening!==null||saving} onClick={remove}>确认删除</Button><Button variant="outline" disabled={opening!==null} onClick={()=>setDeleting(null)}>取消</Button></div>}
 {message&&<output className="history-message" style={{display:"block"}}>{message}</output>}
 {account?.user&&<div className="history-area" id="project-history"><div className="history-toolbar"><h3>我的历史估算</h3><Link className="legacy-link" href="/account/import" onClick={keepDraft}>导入旧版项目</Link><label className="history-search" htmlFor="estimate-search"><Search size={17}/><Input id="estimate-search" aria-label="按项目主题名称搜索" placeholder="搜索项目主题名称" maxLength={80} value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><Button variant="outline" disabled={loading} onClick={()=>setRevision(v=>v+1)}>刷新</Button></div>
 {pending&&<output className="restore-prompt"><span>{pendingEdit?'修改':'载入'}“{pending.title}”（{date(pending.createdAt)}）？当前未保存的修改将被替换。</span><Button disabled={saving||opening!==null} onClick={()=>{onLoad(structuredClone(pending.plan),pending.title);setEditing(pendingEdit?pending:null);submission.current=null;setPending(null);setMessage(pendingEdit?'已进入修改模式，编辑完成后点击“保存修改”。':'已载入历史估算。修改后可保存为新的记录。');}}>{pendingEdit?'确认修改':'确认载入'}</Button><Button variant="outline" onClick={()=>setPending(null)}>取消</Button></output>}
 {loading?<output className="muted" style={{display:"block"}}>正在查询云端记录…</output>:historyError?<p role="alert" className="error-box">{historyError} <Button variant="outline" onClick={()=>setRevision(v=>v+1)}>重试</Button></p>:items.length===0?<p className="history-empty">{query?'没有找到这个主题的记录，请换个关键词。':'还没有保存的估算。填好主题名称，保存你的第一个项目。'}</p>:<ul className="history-list">{items.map(item=><li key={item.id}><div><strong>{item.title}</strong><time dateTime={item.createdAt}>{date(item.createdAt)}</time></div><div className="history-summary"><span>{item.paying} {item.billing==='family'?'组家庭':'位付费'} · ¥{money(item.price)} / {item.billing==='family'?'组':'人'}</span><span>实际成本 <b>¥{money(item.actual)}</b></span><span>实际毛利 <b>¥{money(item.profit)}</b></span></div><div className="history-actions"><Button variant="outline" disabled={opening!==null||saving} onClick={()=>open(item.id)}><FolderOpen size={16}/>载入估算</Button><Button variant="outline" className="history-delete" disabled={opening!==null||saving} onClick={()=>{setDeleting(item);setPending(null);}}><Trash2 size={16}/>删除</Button><Button variant="outline" disabled={opening!==null||saving} onClick={()=>open(item.id,true)}><Pencil size={16}/>修改</Button><Button variant="outline" disabled={opening!==null||saving} onClick={()=>download(item.id)}><Download size={16}/>导出</Button></div></li>)}</ul>}
 <div className="history-pages"><Button variant="outline" disabled={offset===0||loading} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页</Button><span>第 {Math.floor(offset/20)+1} 页</span><Button variant="outline" disabled={!hasMore||loading||!!historyError} onClick={()=>setOffset(v=>v+20)}>下一页</Button></div></div>}
 </section>;
}
