'use client';
import {useEffect,useRef,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
import {Save,Search,Cloud,FolderOpen} from 'lucide-react';
import {money,type Plan} from '@/lib/pricing';
import {parseEstimate} from '@/lib/estimate-input';
type RecordItem={id:string;title:string;createdAt:string;paying:number;price:number;actual:number;profit:number};
type Saved={id:string;title:string;createdAt:string;plan:Plan};
type Account={user:{displayName:string}|null;signIn:string;signOut:string};
const date=(value:string)=>new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
async function request<T=unknown>(url:string,init?:RequestInit){const res=await fetch(url,{...init,cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error((data as {error?:string}).error||'操作失败，请重试');return data as T;}
export function ProjectHistory({plan,title,onTitle,onLoad,valid}:{plan:Plan;title:string;onTitle:(v:string)=>void;onLoad:(p:Plan,t:string)=>void;valid:boolean}){
 const [account,setAccount]=useState<Account|null>(null),[accountError,setAccountError]=useState('');
 const [items,setItems]=useState<RecordItem[]>([]),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[loading,setLoading]=useState(false),[historyError,setHistoryError]=useState(''),[revision,setRevision]=useState(0);
 const [saving,setSaving]=useState(false),[message,setMessage]=useState(''),[opening,setOpening]=useState<string|null>(null),[pending,setPending]=useState<Saved|null>(null);
 const submission=useRef<{body:string;id:string}|null>(null);const loadRef=useRef(onLoad);loadRef.current=onLoad;
 async function loadAccount(){setAccountError('');try{setAccount(await request<Account>('/api/account'));}catch{setAccountError('暂时无法连接账号服务');}}
 useEffect(()=>{void loadAccount();try{const raw=sessionStorage.getItem('pricing-login-draft');if(raw){const value=parseEstimate(JSON.parse(raw));loadRef.current(value.plan,value.title);sessionStorage.removeItem('pricing-login-draft');}}catch{}},[]);
 useEffect(()=>{if(!account?.user)return;const controller=new AbortController();setLoading(true);setHistoryError('');const timer=setTimeout(()=>{request<{items:RecordItem[];hasMore:boolean}>('/api/estimates?q='+encodeURIComponent(query)+'&offset='+offset,{signal:controller.signal}).then(data=>{setItems(data.items);setHasMore(data.hasMore);}).catch(e=>{if(!controller.signal.aborted)setHistoryError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},200);return()=>{clearTimeout(timer);controller.abort();};},[account,query,offset,revision]);
 async function save(){if(saving)return;setMessage('');let value;try{const body=JSON.stringify({title,plan});if(submission.current?.body!==body)submission.current={body,id:crypto.randomUUID()};value=parseEstimate({id:submission.current.id,title,plan});}catch(e){setMessage(e instanceof Error?e.message:'请完善项目参数');return;}setSaving(true);try{await request('/api/estimates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});setMessage('已保存“'+value.title+'”。可在下方历史记录中查询。');setQuery('');setOffset(0);setRevision(v=>v+1);}catch(e){setMessage(e instanceof Error?e.message:'保存失败，请重试');}finally{setSaving(false);}}
 async function open(id:string){setOpening(id);setMessage('');try{setPending(await request<Saved>('/api/estimates?id='+encodeURIComponent(id)));}catch(e){setMessage(e instanceof Error?e.message:'读取失败，请重试');}finally{setOpening(null);}}
 function keepDraft(){try{if(valid)sessionStorage.setItem('pricing-login-draft',JSON.stringify({id:crypto.randomUUID(),title:title.trim()||'未命名项目',plan}));}catch{}}
 return <section className="panel project-library" aria-labelledby="project-library-title"><div className="editor-heading"><div><div className="section-title"><span className="project-folder"><FolderOpen size={21}/></span><h2 id="project-library-title">项目档案</h2><span className="cloud-label"><Cloud size={14}/>云端保存</span></div><p className="muted">为每次估算命名，让历史成本有据可查。</p></div><div className="account-area">{account?.user?<><span>{account.user.displayName}</span><a href={account.signOut} target="_top">退出登录</a></>:account?<a className="signin-link" href={account.signIn} target="_top" onClick={keepDraft}>使用 ChatGPT 登录</a>:accountError?<><span role="alert">{accountError}</span><Button variant="outline" onClick={loadAccount}>重试</Button></>:<span>正在连接账号…</span>}</div></div>
 <div className="project-save"><label className="field"><span>项目主题名称</span><Input maxLength={80} placeholder="例如：秋季自然探索 · 杭州一日研学" value={title} onChange={e=>onTitle(e.target.value)}/></label><Button disabled={!account?.user||saving||!valid||!title.trim()} onClick={save}><Save size={17}/>{saving?'正在保存…':'保存本次估算'}</Button></div>
 <p className="field-note">保存完整参数和成本明细；修改后再次保存会新增记录。未点击保存的修改不会自动同步。{!account?.user&&'计算无需登录，云端保存与查询需要登录。'}</p>
 {message&&<p role="status" className="history-message">{message}</p>}
 {account?.user&&<div className="history-area" id="project-history"><div className="history-toolbar"><h3>我的历史估算</h3><label className="history-search"><Search size={17}/><Input aria-label="按项目主题名称搜索" placeholder="搜索项目主题名称" maxLength={80} value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><Button variant="outline" disabled={loading} onClick={()=>setRevision(v=>v+1)}>刷新</Button></div>
 {pending&&<div className="restore-prompt" role="status"><span>载入“{pending.title}”（{date(pending.createdAt)}）？当前未保存的修改将被替换。</span><Button onClick={()=>{onLoad(structuredClone(pending.plan),pending.title);setPending(null);setMessage('已载入历史估算。修改后可保存为新的记录。');}}>确认载入</Button><Button variant="outline" onClick={()=>setPending(null)}>取消</Button></div>}
 {loading?<p className="muted" role="status">正在查询云端记录…</p>:historyError?<p role="alert" className="error-box">{historyError} <Button variant="outline" onClick={()=>setRevision(v=>v+1)}>重试</Button></p>:items.length===0?<p className="history-empty">{query?'没有找到这个主题的记录，请换个关键词。':'还没有保存的估算。填好主题名称，保存你的第一个项目。'}</p>:<ul className="history-list">{items.map(item=><li key={item.id}><div><strong>{item.title}</strong><time dateTime={item.createdAt}>{date(item.createdAt)}</time></div><div className="history-summary"><span>{item.paying} 位付费 · ¥{money(item.price)} / 人</span><span>实际成本 <b>¥{money(item.actual)}</b></span><span>实际毛利 <b>¥{money(item.profit)}</b></span></div><Button variant="outline" disabled={opening!==null} onClick={()=>open(item.id)}><FolderOpen size={16}/>{opening===item.id?'读取中…':'载入估算'}</Button></li>)}</ul>}
 <div className="history-pages"><Button variant="outline" disabled={offset===0||loading} onClick={()=>setOffset(v=>Math.max(0,v-20))}>上一页</Button><span>第 {Math.floor(offset/20)+1} 页</span><Button variant="outline" disabled={!hasMore||loading||!!historyError} onClick={()=>setOffset(v=>v+20)}>下一页</Button></div></div>}
 </section>;
}
